id = "java"
name = "Java"
version = "2.1.0"
schema_version = 1
authors = [
    "Samuser107 L.Longheval <samuser107@gmail.com>",
    "Valentine Briese <valentinegb@icloud.com>",
    "Yury Abykhodau <abehodau@gmail.com>",
]
description = "Java support."
repository = "https://github.com/zed-extensions/java"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "490d878cf33b0ad5ae7a7253ff30597a5bdc348e"

[language_servers.jdtls]
name = "Eclipse JDT Language Server"
language = "Java"
