id = "java"
name = "Java"
version = "6.2.0"
schema_version = 1
authors = [
    "Valentine Briese <valentinegb@icloud.com>",
    "Samuser107 L.Longheval <samuser107@gmail.com>",
    "Yury Abykhodau <abehodau@gmail.com>",
]
description = "Java support."
repository = "https://github.com/zed-extensions/java"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "94703d5a6bed02b98e438d7cad1136c01a60ba2c"

[grammars.properties]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-properties"
commit = "579b62f5ad8d96c2bb331f07d1408c92767531d9"

[language_servers.jdtls]
name = "Eclipse JDT Language Server"
language = "Java"
