name: zed-tests
on:
  pull_request:
    branches:
      - main
jobs:
  run-extension-tests:
    uses: zed-industries/zed/.github/workflows/extension_tests.yml@main
    with:
      # No tests implemented yet
      run_tests: false
